[package]
name = "escoop"
version = "0.1.0"
edition = "2024"

[dependencies]
clang_log = "2.1.1"
clap = { version = "4.5.40", features = ["derive"] }
colored = "3.0.0"
log = "0.4.27"
peek-again = "0.4.0"
