[package]
name = "escoop"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
codespan-reporting = "0.12.0"
termcolor = "1.4.1"

[profile.profiling]
inherits = "release"
debug = "full"