name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Verify code using Clippy
      run: cargo clippy --verbose
    - name: Verify formatting
      run: cargo fmt --check --verbose
    - name: Run tests
      run: cargo test --verbose

  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build code on Linux
      run: cargo build --verbose

  build_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build code on Windows
      run: cargo build --verbose

  build_macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build code on MacOS
      run: cargo build --verbose
